// generated by umi
declare global {
const React: typeof import('react');

const styles: any;
const createSearchParams: typeof import('umi')['createSearchParams'];
const Link: typeof import('umi')['Link'];
const matchPath: typeof import('umi')['matchPath'];
const matchRoutes: typeof import('umi')['matchRoutes'];
const NavLink: typeof import('umi')['NavLink'];
const Outlet: typeof import('umi')['Outlet'];
const renderClient: typeof import('umi')['renderClient'];
const useAppData: typeof import('umi')['useAppData'];
const useLocation: typeof import('umi')['useLocation'];
const useMatch: typeof import('umi')['useMatch'];
const useNavigate: typeof import('umi')['useNavigate'];
const useOutlet: typeof import('umi')['useOutlet'];
const useParams: typeof import('umi')['useParams'];
const useResolvedPath: typeof import('umi')['useResolvedPath'];
const useRouteData: typeof import('umi')['useRouteData'];
const useRoutes: typeof import('umi')['useRoutes'];
const useSearchParams: typeof import('umi')['useSearchParams']
const createElement: typeof import('react')['createElement']
const createFactory: typeof import('react')['createFactory']
const cloneElement: typeof import('react')['cloneElement']
const isValidElement: typeof import('react')['isValidElement']
const createRef: typeof import('react')['createRef']
const forwardRef: typeof import('react')['forwardRef']
const useState: typeof import('react')['useState']
const useEffect: typeof import('react')['useEffect']
const useContext: typeof import('react')['useContext']
const useReducer: typeof import('react')['useReducer']
const useCallback: typeof import('react')['useCallback']
const useMemo: typeof import('react')['useMemo']
const useRef: typeof import('react')['useRef']
const useImperativeHandle: typeof import('react')['useImperativeHandle']
const useLayoutEffect: typeof import('react')['useLayoutEffect']
const useDebugValue: typeof import('react')['useDebugValue']
}
export {}
