
actions:
  Need Reproduce:
    comment: >
      Hello @{issue-author}
      ---
      为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为无复现步骤或可复现仓库而被自动关闭，提供之后会被 REOPEN。
      ---
      In order to communicate effectively, we have a certain format requirement for the issue, your issue is automatically closed because there is no recurring step or reproducible warehouse, and will be REOPEN after the offer.
    close: true
  -Need Reproduce:
    open: true
