language: node_js

node_js:
  - '8'
  - '10'
  - '12'

install:
  - npm install

before_script:
  - npm run build
  - npm run bootstrap -- --npm-client=npm

after_success:
  - npm run coveralls

cache:
  directories:
    - node_modules

git:
  depth: 5
