sudo: required
language: node_js
addons:
  chrome: stable
env:
  global:
    - HEADLESS=false
    - CI=true
node_js:
  - '8'
  - '10'
  - '12'

before_script:
  - npm run bootstrap
  - npm run build
  - npm run ui:build

script:
  - npm run test -- --forceExit --detectOpenHandles --runInBand

after_success:
  - npm run coveralls

cache:
  directories:
    - node_modules

git:
  depth: 5
