sudo: required
dist: trusty
language: node_js
addons:
  chrome: stable
env:
  global:
    - HEADLESS=false
    - CI=true
    - PROGRESS=none

matrix:
  include:
    - node_js: "8"
    - node_js: "10"
    - node_js: "12"

before_script:
  - npm run bootstrap
  - npm run build
  - npm run ui:build

script:
  - npm run test -- --forceExit --detectOpenHandles --runInBand  --maxWorkers=1

after_success:
  - npm run coveralls

cache:
  directories:
    - node_modules

git:
  depth: 5
