language: node_js

node_js:
  - '8'
  - '10'
  - '12'

before_script:
  - npm run build
  - npm run bootstrap -- --network-timeout 100000

after_success:
  - npm run coveralls

cache:
  directories:
    - node_modules

git:
  depth: 5
