sudo: required
dist: trusty
language: node_js
addons:
  chrome: stable
env:
  global:
    - YARN_GPG=no
    - HEADLESS=false
    - CI=true
    - PROGRESS=none

matrix:
  include:
    - node_js: "8"
    - node_js: "10"
    - node_js: "12"
  fast_finish: true

before_script:
  - yarn bootstrap
  - yarn build
  - yarn ui:build

script:
  - yarn test -- --forceExit --detectOpenHandles --runInBand --maxWorkers=2
  - yarn coveralls

cache:
  yarn: true
  directories:
    - node_modules

git:
  depth: 5
