import { defineConfig, globalIgnores } from '@utoo/lint/config';

export default defineConfig(
  globalIgnores([
    'compiled',
    'devToolAppDist',
    'dist',
    'fixtures',
    'node_modules',
    'vendors',
    'packages/bundler-utoopack/client',
    'packages/bundler-webpack/client',
  ]),
  {
    files: [
      '*.{js,ts}',
      '{codemod,copilot,did-you-know,libs,packages,scripts,ui}/**/*.{js,jsx,ts,tsx,mjs,cjs}',
    ],
    rules: {
      'constructor-super': 'warn',
      'for-direction': 'warn',
      'getter-return': 'warn',
      'no-async-promise-executor': 'warn',
      'no-class-assign': 'warn',
      'no-compare-neg-zero': 'warn',
      'no-const-assign': 'warn',
      'no-debugger': 'error',
      'no-dupe-args': 'warn',
      'no-dupe-class-members': 'warn',
      'no-dupe-else-if': 'warn',
      'no-dupe-keys': 'warn',
      'no-duplicate-case': 'warn',
      'no-ex-assign': 'warn',
      'no-func-assign': 'warn',
      'no-import-assign': 'warn',
      'no-new-native-nonconstructor': 'warn',
      'no-obj-calls': 'warn',
      'no-promise-executor-return': 'warn',
      'no-self-assign': 'warn',
      'no-setter-return': 'warn',
      'no-this-before-super': 'warn',
      'no-unreachable': 'warn',
      'no-unreachable-loop': 'warn',
      'no-unsafe-finally': 'warn',
      'no-unsafe-negation': 'warn',
      'no-unsafe-optional-chaining': 'warn',
      'no-unused-private-class-members': 'warn',
      'require-yield': 'warn',
      'use-isnan': 'warn',
      'valid-typeof': 'warn',
    },
  },
);
