import address from '@umijs/deps/compiled/address';
import chalk from '@umijs/deps/compiled/chalk';
import spawn from '@umijs/deps/compiled/cross-spawn';
import * as chokidar from '@umijs/deps/reexported/chokidar';
import clipboardy from '@umijs/deps/reexported/clipboardy';
import createDebug, { Debugger } from '@umijs/deps/compiled/debug';
import deepmerge from '@umijs/deps/compiled/deepmerge';
import execa from '@umijs/deps/compiled/execa';
import lodash from '@umijs/deps/compiled/lodash';
import glob from '@umijs/deps/compiled/glob';
import portfinder from '@umijs/deps/compiled/portfinder';
import got from '@umijs/deps/compiled/got';
import resolve from '@umijs/deps/compiled/resolve';
import yargs from '@umijs/deps/compiled/yargs';
import mkdirp from '@umijs/deps/compiled/mkdirp';
import pkgUp from '@umijs/deps/compiled/pkg-up';
import prompts from '@umijs/deps/compiled/prompts';
import Mustache from '@umijs/deps/compiled/mustache';
import signale from '@umijs/deps/compiled/signale';
import rimraf from '@umijs/deps/compiled/rimraf';
import yParser from '@umijs/deps/compiled/yargs-parser';
import * as t from '@umijs/deps/compiled/babel/types';
import * as parser from '@umijs/deps/compiled/babel/parser';
import * as traverse from '@umijs/deps/compiled/babel/traverse';
import semver from '@umijs/deps/compiled/semver';

export { spawn };
export { semver };
export { address };
export { chalk };
export { default as cheerio } from './cheerio/cheerio';
export { clipboardy };
export { chokidar };
export { createDebug, Debugger };
export { deepmerge };
export { execa };
export { lodash };
export { glob };
export { got };
export { prompts };
export { portfinder };
export { pkgUp };
export { resolve };
export { yargs };
export { mkdirp };
export { Mustache };
export { rimraf };
export { yParser };
export { t };
export { parser };
export { traverse };
export { signale };

export * from './ssr';
export * from './routes';
export { default as compatESModuleRequire } from './compatESModuleRequire/compatESModuleRequire';
export { default as mergeConfig } from './mergeConfig/mergeConfig';
export { default as isLernaPackage } from './isLernaPackage/isLernaPackage';
export { default as getFile } from './getFile/getFile';
export { default as winPath } from './winPath/winPath';
export { default as winEOL, isWindows } from './winEOL/winEOL';
export { default as parseRequireDeps } from './parseRequireDeps/parseRequireDeps';
export { default as BabelRegister } from './BabelRegister/BabelRegister';
export { default as Generator } from './Generator/Generator';
export { default as randomColor } from './randomColor/randomColor';
export { default as delay } from './delay/delay';
export { default as cleanRequireCache } from './cleanRequireCache/cleanRequireCache';
export * from './types';
